---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      name: etcd
  template:
    metadata:
      labels:
        name: etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:latest
          command:
            - '/usr/local/bin/etcd'
            - '--advertise-client-urls'
            - 'http://0.0.0.0:2379'
            - '--listen-client-urls'
            - 'http://0.0.0.0:2379'
          ports:
            - name: etcd
              containerPort: 2379
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  type: ClusterIP
  selector:
    name: etcd
  ports:
    - name: etcd
      port: 2379
      targetPort: 2379
